
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ATTR CLOSETAG OPENTAGelement : OPENTAG attributes CLOSETAG\n               | OPENTAG CLOSETAGattributes : ATTR attributes\n                  | ATTR'
    
_lr_action_items = {'OPENTAG':([0,],[2,]),'$end':([1,4,6,],[0,-2,-1,]),'CLOSETAG':([2,3,5,7,],[4,6,-4,-3,]),'ATTR':([2,5,],[5,5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'element':([0,],[1,]),'attributes':([2,5,],[3,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> element","S'",1,None,None,None),
  ('element -> OPENTAG attributes CLOSETAG','element',3,'p_element','Parser.py',28),
  ('element -> OPENTAG CLOSETAG','element',2,'p_element','Parser.py',29),
  ('attributes -> ATTR attributes','attributes',2,'p_attributes','Parser.py',33),
  ('attributes -> ATTR','attributes',1,'p_attributes','Parser.py',34),
]
